console.log('test');
var  myAge = 30;
console.log(myAge);
var my_firstName="John";
console.log(my_firstName);
var num = "12";
console.log(typeof + num);
// console.log(typeof Number(num));
var str = 1;
console.log(typeof String(str));
console.log(10 + "20");
console.log(9 - "5");
console.log("Java" + "Script");
console.log(" " + " ");
console.log(" " + 0);
console.log("vinod" - "thapa");
console.log(true + true);
console.log(true + false);
console.log(false + true);
console.log(false - true);
let sum = "15" + 5;
console.log(sum);